name: Docker Image CI

on:
  push:
    branches: [ "main", "Stage" ]
  pull_request:
    branches: [ "main", "Stage" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PROD: nebo_task
          ECR_REPOSITORY_STAGE: nebo_task_stage
          BRANCH_NAME: ${{ github.ref_name }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ID: ${{ github.run_id }}
        run: |
          # Sanitize branch name (replace / with -)
          SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '/' '-')
      
          IMAGE_TAG=docker_image_${SAFE_BRANCH}_${RUN_NUMBER}_${RUN_ID}
          echo "üè∑Ô∏è Using tag: $IMAGE_TAG"
      
          # Build the image
          docker build -t $IMAGE_TAG .
      
          # Push to PROD if main branch
          if [ "$SAFE_BRANCH" = "main" ]; then
            docker tag $IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_PROD:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY_PROD:$IMAGE_TAG
      
            # Also push 'latest' tag for convenience
            docker tag $IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_PROD:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY_PROD:latest
          fi
      
          # Push to STAGE if Stage branch
          if [ "$SAFE_BRANCH" = "Stage" ]; then
            docker tag $IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY_STAGE:$IMAGE_TAG
            docker push $ECR_REGISTRY/$ECR_REPOSITORY_STAGE:$IMAGE_TAG

          fi
      
          echo "‚úÖ Image pushed successfully with tag: $IMAGE_TAG"
